module.exports = {
    content: ["./src/**/*.js"],
    safelist: [
        'yst-col-start-1',
        'yst-col-start-2',
        'yst-col-start-3',
        'yst-col-start-4',
        'yst-col-start-5',
        'yst-col-start-6',
        'yst-col-start-7',
        'yst-col-start-8',
        'yst-col-start-9',
        'yst-col-start-10',
        'yst-col-start-11',
        'yst-col-start-12',
        'yst-col-span-1',
        'yst-col-span-2',
        'yst-col-span-3',
        'yst-col-span-4',
        'yst-col-span-5',
        'yst-col-span-6',
        'yst-col-span-7',
        'yst-col-span-8',
        'yst-col-span-9',
        'yst-col-span-10',
        'yst-col-span-11',
        'yst-col-span-12',
        'yst-col-end-1',
        'yst-col-end-2',
        'yst-col-end-3',
        'yst-col-end-4',
        'yst-col-end-5',
        'yst-col-end-6',
        'yst-col-end-7',
        'yst-col-end-8',
        'yst-col-end-9',
        'yst-col-end-10',
        'yst-col-end-11',
        'yst-col-end-12',
        'yst-col-end-13',
    ],
    theme: {
        fontSize: {
            xxs: "0.6rem",
            xs: ".75rem",
            sm: ".8125rem",
            tiny: ".875rem",
            base: "1rem",
            lg: "1.125rem",
            xl: "1.25rem",
            "2xl": "1.5rem",
            "3xl": "1.875rem",
            "4xl": "2.25rem",
            "5xl": "3rem",
            "6xl": "4rem",
            "7xl": "5rem",
        },
        extend: {
            colors: {
                primary: {
                    50: "#faf4f8",
                    100: "#f6eaf0",
                    200: "#e8c9da",
                    300: "#dba9c3",
                    400: "#bf6997",
                    500: "#a4286a",
                    600: "#94245f",
                    700: "#7b1e50",
                    800: "#621840",
                    900: "#501434",
                },
            },
        },
    },
    variants: {
        extend: {
            backgroundColor: ["active", "group-focus", "disabled"],
            borderWidth: ["first", "last"],
            borderRadius: ["first", "last"],
            textColor: ["active", "group-focus"],
            margin: ["last"],
        },
    },
    plugins: [],
    prefix: "yst-",
};